/**
 * Types for the virtual modules generated by `vite/poseAssetsPlugin.js`.
 * Each pose module is built from a folder of PNGs under `public/`.
 */

declare module "*pose-assets" {
	export type PoseAsset = {
		/** Pose name derived from the file name: `pos_wall_right.png` → `wall-right`. */
		pose: string;
		file: string;
		src: string;
	};

	export const POSE_ASSETS: PoseAsset[];
	export const POSE_SRC: Record<string, string>;
	export const POSE_KEYS: string[];
}

declare module "virtual:museum-exhibits" {
	export type MuseumExhibitAsset = {
		/** Where the art hangs: on a wall, or on top of a pedestal. */
		kind: "picture" | "pedestal";
		/** Project slug from the file name: `plant_tracker_13.png` → `plant_tracker`. */
		slug: string;
		/** Numbered stand the art belongs to, 1–15. */
		stand: number;
		file: string;
		src: string;
	};

	export const MUSEUM_EXHIBITS: MuseumExhibitAsset[];
}
